### PR TITLE
use org instead of tenant

### PR DESCRIPTION
**Pull request by dschep**
includes major version bump since this is a breaking change

### CODE REVIEW

**Comment by dschep** [comment]
So urls won't change?

**Comment by plfx** [comment]
@dschep In planning we decided to leave any API-integration changes for the backend story. For this story, can we just change
- any language and messages presented to the user
- the reading of the config, which should use either `org` or `tenant`, whichever is present in **serverless.yml**

**Comment by dschep** [comment]
doh 🤦‍♂

**Comment by dschep** [comment]
no changs here then. plugin pr only

**Pull request closed without merging**
