### PR TITLE
regenerator-runtime instead of babel-polyfill

### PR DESCRIPTION
**Pull request by dschep**
closes #24

### CODE REVIEW

**Comment by paolopiaggio** [comment]
nice PR @SalvatorePreviti
;)

**Comment by dschep** [comment]
nevermind. can't do this bc babel-polyfill is needed for things like `Object.values` & `Object.entries` in older node versions

**Comment by SalvatorePreviti** [comment]
I see. Would you like a PR where the code is refactored to work on old node version without the use of core-js?

**Comment by SalvatorePreviti** [comment]
Another option would be to load core-js only if node is is less than 8.10.0

**Comment by dschep** [comment]
> where the code is refactored to work on old node versions without the use of core-js or regenerator-runtime

meaning, something like using `_.entries` and `_.values` instead of functions that need to be polyfilled?

If so, I think I prefer your second suggestion (version based loading)

**Pull request closed without merging**
